### ISSUE TITLE
update oncokb.sql

### ISSUE THREAD

**Issue by priti88** [oncokb/oncokb#1055]
Please give as much information as possible before submitting your issue - Thank you

Issue: oncokb.sql is not updated, Error: Unknown name value for enum class org.mskcc.cbio.oncokb.model.EvidenceType: NCCN_GUIDELINES

Example:

Screenshot:

**Comment by zhx828** [comment]
Issue has been solved in https://github.com/oncokb/oncokb/pull/1056
