### ISSUE TITLE
Curation platform firebase refactor issue trackers

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#1084]
- [x] warnings not working correctly
- [x] 3A IS can’t pick 4 propagation
- [x] go to review mode directly when first enter the page
- [x] tumor duplication check is not working when editing
- [x] can’t switch to new main type without clearing the subtypes
- [x] check oncotree version is same
- [x] don’t open after moving mutation
- [x] change to replace mutation index
- [x] add color to indicate moved mutation
- [x] can not approved newly added tumor

**Comment by MoriahNissan** [comment]
The tool to move things around (i.e. reorder tumor types) is very counter-intuitive. I clicked on the crossed arrows of the drug i wanted to move, which highlighted arrows in the OTHER drugs, but not in the drug I wanted to move. And do the arrows in the other drugs only move in reference to the drug that is highlighted? It is very confusing.

![image](https://user-images.githubusercontent.com/20099031/42172453-fcd25b60-7de9-11e8-8631-54a29be40cff.png)

**Comment by MoriahNissan** [comment]
Would it be possible to indicate on the tumor type which of them have tumor type summaires? currently it's only on the mutation header

![image](https://user-images.githubusercontent.com/20099031/42173521-52000bb6-7ded-11e8-98cd-9d63316a1b47.png)

**Comment by MoriahNissan** [comment]
There is a bug somewere that distorts the PDF of any gene that uses greek symbols in the text. Since we use greek symbols frequently and since I use the PDFs as a tool to search for information in the gene page, would you be able to fix this?

![image](https://user-images.githubusercontent.com/20099031/42174705-3df23b9a-7df1-11e8-953e-fc549eebf5e4.png)

**Comment by MoriahNissan** [comment]
When I try to reject this change in the system, the "X" will turn green (suggesting that the change was rejected) but it will keep the change and just continue to say that it is unreviewed when i go back into review mode

![image](https://user-images.githubusercontent.com/20099031/42238190-0587aee2-7ece-11e8-95ff-7f25f12d074e.png)

**Comment by MoriahNissan** [comment]
Tumor Type Summary Count no longer displays on the mutation header or on the tumor type header. The only thing that displays is "undefined1x"

![image](https://user-images.githubusercontent.com/20099031/42238844-26a362cc-7ed0-11e8-9426-321993004a5a.png)

**Comment by MoriahNissan** [comment]
Even though I added (fake) tumor types with standard and investigational therapeutics and tumor type summaries in each, no indication of that (i.e. "2xTT Level 1) appears on the mutation header after i review and accept the new data

![image](https://user-images.githubusercontent.com/20099031/42239249-5a820944-7ed1-11e8-9fd8-1044f6d80be3.png)

**Comment by MoriahNissan** [comment]
"Variant Annotation" Feature does not work

![image](https://user-images.githubusercontent.com/20099031/42242435-daaa8f7e-7edb-11e8-9de2-393dd3a2e8eb.png)

**Comment by JiaoJiao123** [comment]
- [ ] moving sections generate content in review mode

**Comment by JiaoJiao123** [comment]
- [ ] delete mutation can’t enter review mode
-[ ] and not yet reviewed. in red
home page, eye icons
sort by reviewed at history model
query reviewed options not working, chosed mutation_effect but returned tumor type summary
change drug names not working. old content is not displayed and can’t accept it
hide Tis if not treatment is added in newly added mutation

**Comment by JiaoJiao123** [comment]
Things listed here are solved, except the Greek letter in PDF issue, which is not urgent and takes time to re-implement this feature. So we paused fixing it.
