### ISSUE TITLE
OncoKB DB Test- history empty records

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1133]
Please give as much information as possible before submitting your issue - Thank you

Issue: The dates on the gene review history are not accurate, and not all the changes are shown here - we just worked extensively on this gene this week.

Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/42103066-f0853252-7b95-11e8-925d-19bf08fb67ed.png)

**Comment by JiaoJiao123** [comment]
Solved
