### ISSUE TITLE
OncoKB DB Test

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1134]
Please give as much information as possible before submitting your issue - Thank you

Issue:  When I was in the curation queue page, and I tried to delete an entry, the mouse and icon kept blinking

Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/42104118-6d77e52c-7b99-11e8-8cb9-61d4483254f5.png)

**Comment by JiaoJiao123** [comment]
solved
