### ISSUE TITLE
OncoKB Database Test

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1143]
Please give as much information as possible before submitting your issue - Thank you

Issue: When I changed a level, and accepted it in review mode, the mutation header still shows the old level.

Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/42119099-b179ffca-7bd6-11e8-81c1-661f8ca73640.png)

**Comment by JiaoJiao123** [comment]
fixed in PR #1158
