### ISSUE TITLE
review warning pops up even w/o other ppl on the doc 

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#1150]
![image](https://user-images.githubusercontent.com/840895/42240201-8b52c678-7ed4-11e8-9e0e-f34dd161957c.png)

**Comment by JiaoJiao123** [comment]
This is solved. We can track currentReviewer and collaborators precisely now. The warning buttons are replaced with a red text message at the top of the gene page to indicate currentReviewer information.
