### ISSUE TITLE
Changing drug names

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#1180]
Please give as much information as possible before submitting your issue - Thank you

Issue: When I change a drug name, and accept under Review mode, the change doesn't go through

Example: In the ABL1 gene, under Mutation: D276G, Investigational Implications for Resistance, changed BGJ398 to Dasatinib

Screenshot:
![image](https://user-images.githubusercontent.com/17145213/42583358-cb1a2758-84fe-11e8-88fe-0b0a0f6c7222.png)
![screen shot 2018-07-11 at 11 37 30 am](https://user-images.githubusercontent.com/17145213/42583378-d4bcf588-84fe-11e8-907a-e35242b826c0.png)
![image](https://user-images.githubusercontent.com/17145213/42583401-df9b43ba-84fe-11e8-8370-d821a36c7332.png)

**Comment by JiaoJiao123** [comment]
Solved and tested.
