### ISSUE TITLE
Tumor type is not removed and review mode is triggered with weird content

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1210]
The `All Tumors` is not removed when first time tried to remove it, and in the review mode, it shows as empty content as new content.
![jul-12-2018 19-32-20](https://user-images.githubusercontent.com/5400599/42664742-59ae4754-860a-11e8-8fd0-720cbadc30ac.gif)

**Comment by JiaoJiao123** [comment]
@zhx828 ok get it. I will look into this

**Comment by JiaoJiao123** [comment]
@zhx828 I can't reproduce this. I tested tumor type editing and related review mode feature, it works fine. Please let me know if you could reproduce this.

**Comment by zhx828** [comment]
@jjgao I can't reproduce the issue either, close the ticket for now.
