### ISSUE TITLE
The tooltip continue blinking

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1211]
I can give you a demonstration tomorrow
![jul-12-2018 19-42-22](https://user-images.githubusercontent.com/5400599/42665008-bacbb480-860b-11e8-8da9-d07839acb63d.gif)

**Comment by JiaoJiao123** [comment]
@zhx828 should be fine now after we switch ng-if to ng-show. http://dashi-dev.cbio.mskcc.org:8080/curate/#!/genes
