### ISSUE TITLE
Treatment priority is not updated when modify the treatments in the same Therapy section

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1240]
When you have A, B  in the therapy section, the priority is A:1, B:2. After changing the order to B, A, it will not update the priorities. It should be A:2, B:1

**Comment by victoria34** [comment]
In current system, we won't record order change in review mode.

**Comment by zhx828** [comment]
Not moving therapeutic, it is when you have two treatments listed together
in the same section. They will have different priorities too.

**Comment by victoria34** [comment]
Cannot reproduce this issue.
