### ISSUE TITLE
When material is deleted it does not show in the Old Content as being deleted - there is no entry

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#1254]
Sarah deleted content from G719, but in review mode it showed like this:

New Content:

Old Content:
__________________________________________________________

Whereas it should show like this:

New Content:

Old Content:
~~This is the content that Sarah deleted.~~

**Comment by JiaoJiao123** [comment]
@victoria34 Could you please look into this? Let me know if you need any help
