### ISSUE TITLE
Variant in portal called oncogenic/hotspot but not showing up with hotspot icon

### ISSUE THREAD

**Issue by MoriahNissan** [oncokb/oncokb#1263]
Please give as much information as possible before submitting your issue - Thank you

Issue: 

Example:

Screenshot: 
![image](https://user-images.githubusercontent.com/20099031/43013548-3f2a3e2a-8c17-11e8-9265-15061df664b5.png)

![image](https://user-images.githubusercontent.com/20099031/43013529-324d2cc6-8c17-11e8-8891-43d0a2618e02.png)

**Comment by zhx828** [comment]
Some hotspots are manually removed from the hotspot list in Genome Nexus. And we are now using GenomeNexus to annotate hotspot as well. So the issue is resolved.
