### ISSUE TITLE
Domain specific annotation showing in cBioPortal, not the mutation specific annotation

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#1273]
Issue: The TP53 P191del mutation occurs in the TP53 DNA binding domain, so the following annotation can capture this mutation:
![image](https://user-images.githubusercontent.com/17145213/43148671-ca247b2a-8f33-11e8-81ab-f56f7eaf98e0.png)

However, I specifically curated this mutation:

![image](https://user-images.githubusercontent.com/17145213/43148703-d94d479e-8f33-11e8-80c2-009d47d0e1d0.png)

But in the portal, the annotation for the DNA-binding domain mutation as opposed to the mutation specific annotation is showing up:
![image](https://user-images.githubusercontent.com/17145213/43148724-e6098d76-8f33-11e8-8e3f-b22304149bad.png)

**Comment by zhx828** [comment]
Check in the portal, this variant is annotated on protein start 191, protein end 192. That's why it picked up `DNA binding domain` instead. Will contact portal group to fix the data.
