### ISSUE TITLE
Seems sorting by Last modified is not working properly

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1277]
![jul-24-2018 13-45-55](https://user-images.githubusercontent.com/5400599/43156417-079083aa-8f48-11e8-820c-8117478fea56.gif)

**Comment by victoria34** [comment]
That's because you click `Last modified by` first. The column is sorting in ascending order and GENEs without modified record are listed in the header. When you click `Last modified` later, the sorting result will be relied on the current table so you see lots of empty cells are listed first.

**Comment by zhx828** [comment]
No matter how I click on the column, I'm expecting to see the same result.
According to the screenshot apparently it's not the case.
