### ISSUE TITLE
Match cancer.gov and oncokb drugs and used in portal

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1311]
- [x] Python Script: Match trails based on the drug 
- [x] Built API swagger page
- [x] Created Node.js API for querying matched trials by patient cancer type and OncoKB treatments  
- [x] cbioportal-frontend: Clinical Trial card feature
- [x] Deploy API on Kubernetes

**Comment by victoria34** [comment]
Mockup version 1:

![Screen Shot 2020-02-17 at 7 06 05 PM](https://user-images.githubusercontent.com/14971266/75715858-22fed100-5c9c-11ea-8cea-512bd05521f0.png)

**Comment by victoria34** [comment]
Mockup version 2:

![Screen Shot 2020-02-17 at 7 06 05 PM](https://user-images.githubusercontent.com/14971266/75715858-22fed100-5c9c-11ea-8cea-512bd05521f0.png)

**Comment by victoria34** [comment]
Mockup version 3:
Short trial title view:

Full trial title view:
![image](https://user-images.githubusercontent.com/14971266/75819859-58bdbb80-5d69-11ea-98f3-a3f12fdd9f14.png)

**Comment by victoria34** [comment]
Mockup version 4:
![Screen Shot 2020-03-04 at 3 22 20 PM](https://user-images.githubusercontent.com/14971266/75919683-faa5dc80-5e2b-11ea-8b8a-2538a55f529c.png)

**Comment by victoria34** [comment]
Clinical Trials Tab:

![image](https://user-images.githubusercontent.com/14971266/76131143-52367a80-5fdb-11ea-8050-b2d8dd8546f7.png)

**Comment by zhx828** [comment]
The prototyping of the portal integration has done. But we no longer pulling data from cancer.gov since it only includes the NCI supported trials. This Epic https://github.com/oncokb/oncokb/issues/2434 is the current main tracker. Closing this one to resolve the confusion.
