### ISSUE TITLE
Two gene pages for the same gene

### ISSUE THREAD

**Issue by MoriahNissan** [oncokb/oncokb#1344]
Please give as much information as possible before submitting your issue - Thank you

Issue: We have a gene page for PAK5 (the gene that encoded PAK7) and also a page for the gene PAK7 (which is the same as PAK5). Please delete the empty gene page for PAK7.

Example:

Screenshot:
![image](https://user-images.githubusercontent.com/20099031/44362276-79c40180-a48e-11e8-8883-4d1ed9ee174f.png)

**Comment by zhx828** [comment]
Just FYI, PAK5 is the latest symbol used in the portal. However MSK IMPACT 468 genes panel uses PAK7. The follow ing few things need to be done:
- [ ] Add PAK7 in gene alias
- [ ] Double check it is ok showing PAK5 in the gene summary in the MSK report
- [ ] Remove PAK7 from curation system
- [ ] Update cancer genes list

**Comment by zhx828** [comment]
This relates to https://github.com/oncokb/oncokb/issues/1253
