### ISSUE TITLE
Deploying dev env

### ISSUE THREAD

**Issue by CezCz** [oncokb/oncokb#1378]
I've tried to deploy this application, and ran into some troubles. Could you help me to clarify following issues ?

Issue: Troubles with deploying frontend and backend application

Problems with deploying frontend: 
- two libraries (firepad, codemirror) are not installed with neither node or bower, have to install them manually. (please see screenshot)
- After installing it there's error from firebase - "Your API key is invalid, please check you have copied it correctly."
- Webpage displays "You are using Internet Explorer which has not yet been sup...", which is probably result of previous error as website is not starting to run.
- grunt test is not running at all, gets stuck right after typing the command.

Could you guide how to proceed from now? I don't want to configure Google Api connection yet.

Problems with deploying backend:
- Are there guidelines how to deploy dev backend ?
- I've noticed that a AlterationUtilsTest take considerable amount of time (caching) to run and some of test in SummaryUtilsParametrizedTest (94) are failing. Is it just on my machine?

Screenshot:
![image](https://user-images.githubusercontent.com/11783702/45742481-637aa400-bbfa-11e8-864d-477982757d2d.png)

**Comment by victoria34** [comment]
Hi @CezCz, we just use Google Firebase to replace Google Realtime API since Google Realtime API will be deprecated in Jan 2019. We also updated README.md but we haven't merged it into master branch. Sorry for bringing inconvenience to you. Please follow README.md in branch release-0.3.3 and you should be fine.
