### ISSUE TITLE
Code test coverage

### ISSUE THREAD

**Issue by CezCz** [oncokb/oncokb#1379]
Please give as much information as possible before submitting your issue - Thank you

Issue:  Code test coverage
I cannot run tests, could you provide your code test coverage?

**Comment by victoria34** [comment]
For front-end test, please follow README.md in branch release-0.3.3.
![screen shot 2018-09-20 at 4 12 42 pm](https://user-images.githubusercontent.com/14971266/45844332-14af3600-bcf0-11e8-8864-d331b104b09b.png)

**Comment by CezCz** [comment]
Thank you for clarification
