### ISSUE TITLE
new endpoint `variant-annotation`

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#1390]
Let's have a `variant-annotation` group of endpoints. The goal is to have a simplified set of APIs that can replace the `/search` endpoint. (we can continue to support `/search` for a while but maybe mark it as deprecated once we have `variant-annotation`).

I propose to have the following endpoints:

- `/annotate/mutations/byProteinChange`
- `/annotate/mutations/byGenomicChange`
- `/annotate/mutations/byHGVSg`
- `/annotate/copyNumberAlterations`
- `/annotate/structuralVariants`

The input of the APIs would be similar to `POST /search` but we should only include the relevant parameters for different ones in `queries` field, e.g. `byHGVSg` would only have `hgvsg`.

The output should contain a list of annotated results, one per mutation/cna/sv, similar to the current output.

**Comment by zhx828** [comment]
@jjgao could you give me an example how the genomic change endpoint will be used? Specifically the model.

**Comment by jjgao** [comment]
@zhx828 it should be similar to genome nexus: http://genomenexus.org/swagger-ui.html#!/annotation45controller/fetchVariantAnnotationByGenomicLocationGET

http://genomenexus.org/annotation/genomic/7%2C140453136%2C140453136%2CA%2CT
