### ISSUE TITLE
New HashSet takes too much time

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1408]
In the last fix when we try to avoid the object to be modified, instead of returning the object, we create a new HashSet which takes a lot of time.

**Comment by zhx828** [comment]
Issue was introduced in https://github.com/oncokb/oncokb/pull/1381/files

**Comment by jjgao** [comment]
@zhx828 please try `return Collections.unmodifiableSet(result)` instead of creating a new one.
