### ISSUE TITLE
Support hgvsg for variant page

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#1410]
Currently, we support protein alteration:

https://www.oncokb.org/gene/BRAF/V600E

It would be good to support hgvsg as well.

for example:

- https://www.oncokb.org/hgvsg/7:g.140753336A>T?refGenome=GRCh38
- https://www.oncokb.org/hgvsg/7:g.140453136A>T?refGenome=GRCH38

We can support both GRCh38/hg38 and GRCh37/hg19.

We can utilize vep variant_recoder for convert the genomic location to protein.

GRCh38: https://rest.ensembl.org/variant_recoder/human/NC_000007:g.140753336A>T?content-type=application/json

They also support versioning: https://rest.ensembl.org/variant_recoder/human/NC_000007.14:g.140753336A>T?content-type=application/json

GRCh37: https://grch37.rest.ensembl.org/variant_recoder/human/NC_000007:g.140453136A>T?content-type=application/json

Maybe we can support all kinds of IDs specified by variant_recoder?

- https://www.oncokb.org/hgvsc/ENST00000496384:c.1799T>A?refGenome=GRCh38
	- if OncoKB is using a different transcript, we should add a note on the page
- https://www.oncokb.org/hgvsp/ENSP00000419060:p.Val600Glu?refGenome=GRCh38
	- if OncoKB is using a different transcript/protein, we should add a note on the page
- https://www.oncokb.org/dbsnp/rs113488022
	- refGenome is not needed, but we can send to grch38 version of variant_recoder

**Comment by zhx828** [comment]
@jjgao do we still want to support this?

**Comment by jjgao** [comment]
@jjgao yes, we do. But maybe as part of the new variant page as discussed?

**Comment by jjgao** [comment]
@inodb do you think we can support GRCh38/hg38 soon in Genome Nexus?

**Comment by jjgao** [comment]
@zhx828 let's prioritize this one. Since we don't have hg38 support in genome nexus yet, let's use VEP directly for the moment.

**Comment by jjgao** [comment]
I just noticed that Ensembl now has variant recorder, which may be a useful tool for our use case:

http://rest.ensembl.org/variant_recoder/human/NC_000007:g.140753336A%3ET?content-type=application/json

**Comment by jjgao** [comment]
@zhx828 for mapping from ENST to ENSP, you can use biomart: http://useast.ensembl.org/biomart/martview/

It may be good idea to map for both grch37 and grch38 and see if there are discrepancies.

**Comment by jjgao** [comment]
We could also use this endpoint in genome nexus: https://www.genomenexus.org/ensembl/transcript/ENST00000496384

I am not sure if the mapping would be different between grch37 and grch38, so it may be a good idea to do the biomart mapping anyway.

**Comment by jjgao** [comment]
@zhx828 do you think we have the bandwidth to prioritize this? I remember we got stuck on the step of defining the transcript IDs for hg38.

**Comment by zhx828** [comment]
@jjgao right. We do not have a better way to convert between hg38/hg37. I need to follow up with GN group to see what the current status is.

**Comment by jjgao** [comment]
@zhx828 we may have to curate the canonical transcript list (for both gn and oncokb) for hg38. For example, we could compare transcript sequences between hg37 and hg38.

**Comment by zhx828** [comment]
@jjgao sure, do you think I should take over that work or the GN group should do the curation. I know the portal team is working on the gene list. Maybe it's related?

**Comment by jjgao** [comment]
@zhx828 if you have the bandwidth, could you look into it? I have some ideas on how to proceed. Let's have a discussion.

The gene list for the portal is different.

**Comment by zhx828** [comment]
This ticket is related https://github.com/genome-nexus/genome-nexus/issues/306

**Comment by zhx828** [comment]
- We do not have a proper way to annotate hgvsp if the isoform is not the same as oncokb.
- dbsnp is too complex to visualize and current is not our priority
