### ISSUE TITLE
add Gene download button

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#1428]
Add a button (the first one) `ALL CURATED GENES` to download genes. Let's include: 

- HUGO SYMBOL
- ENTREZ GENE ID
- ENSEMBL TRANSCRIPT ID
- REFSEQ TRANSCRIPT ID
- IS A TUMOR SUPPRESSOR GENE
- IS AN ONCOGENE
- HIGHEST LEVE OF EVIDENCE (SENSITIVITY)
- HIGHEST LEVE OF EVIDENCE (RESISTANCE)
- SUMMARY

![image](https://user-images.githubusercontent.com/840895/49545431-9b18f400-f8ab-11e8-8148-485c1ad41e6b.png)

cc'ing @debyani-chakravarty @schultzn

**Comment by debyani-chakravarty** [comment]
Could we also include for each gene whether or not it's a TSG or OG?
