### ISSUE TITLE
retire root domain oncokb.org

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#1434]
By @inodb:

Just wanted to mention this here as well - we pointed www.oncokb.org to AWS. It will take a while for the new DNS changes to propagate thru msk network. But on my phone I can already reach it.

One thing we should try to avoid in the future is to point root domains to instances, e.g. oncokb.org -> ip. Just use www.oncokb.org -> ip and forward oncokb.org -> www.oncokb.org. This is what Google does as well so must be the right way :slightly_smiling_face:

You can’t put a CNAME record on the root domain, so pointing it to e.g. appname.heroku.com or loadbalancer.aws.com is not possible. There are a lot of these services that don’t offer a static ip and a CNAME record is really the only way to make it work.

This is the reason why we were having some issues with cancerhotspots when we moved it to heroku. All cBioPortal frontend POST requests were going to cancerhotspots.org instead of www.cancerhotspots.org. Unf you can’t forward a POST request. For backwards compatibility we were therefore running one instance locally at cancerhotspots.org and another on heroku at www.cancerhotspots.org. After a while we retired cancerhotspots.org and just forwarded it to www.cancerhotspots.org.

We did however receive a lot of emails and slack messages about e.g. cancerhotspots.org being down, while www.cancerhotspots.org was working fine. So not a v pleasant user experience

For OncoKB we were able to get around this issue by making Google Domains use the AWS nameservers. This does allow you to point the root domain to an AWS loadbalancer (AWS does know the dynamic ip of the loadbalancer, so it can route the the traffic accordingly). This way we were able to continue to support sending POST requests to oncokb.org. We’ve also enabled www.oncokb.org . At some point we will prolly retire oncokb.org and forward that to www.oncokb.org instead.

**Comment by zhx828** [comment]
Update:
All requests to oncokb.org will be redirected to www.oncokb.org on the app level. I will follow up with Ino with next steps.

**Comment by zhx828** [comment]
This is actually done. http://oncokb.org, https://oncokb.org, http://www.oncokb.org all giving `308 permanently moved` http code and redirect to https://www.oncokb. org
