### ISSUE TITLE
Any rearrangement event in a tumor suppressor should be considered likely oncogenic

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1495]

**Comment by jjgao** [comment]
If we are mapping SVs to Truncating mutations, I don’t think we need special rules for tumor suppressors. (If a tumor suppressor does not have Truncating Mutations annotated, we should not annotate SVs as likely oncogenic.)

**Comment by zhx828** [comment]
Base on JJ's comment, we don't need to do anything.
