### ISSUE TITLE
filtering for specific mutations in lollipop plot doesn't update table

### ISSUE THREAD

**Issue by tmazor** [oncokb/oncokb#1626]
If I click on a lollipop, text appears saying that the current view shows filtered results, but the table doesn't filter.

Here, I selected the lollipop for T790M, but all mutations are still visible:
![image](https://user-images.githubusercontent.com/10508276/59220370-ce0dae80-8b92-11e9-8221-370f934f6618.png)

Similarly, filtering the table doesn't update the lollipop plot:
![image](https://user-images.githubusercontent.com/10508276/59220397-debe2480-8b92-11e9-97af-ac8787776f8f.png)

https://oncokb.org/gene/EGFR

**Comment by zhx828** [comment]
@tmazor this issue has been address. Thanks for reporting the issue!
