### ISSUE TITLE
Update the records section in the Review History tool

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1671]
Some of the fields are not necessary to show by default.

TIs, *_review, *_uuid(the Include UUID checkbox is not selected, this seems to be a bug?)

**Comment by victoria34** [comment]
The "Include UUID" checkbox should be removed. For those fields you mentioned, they are all stored in new content or old content. The data structure of old content and new content are not fixed, so I display the whole *_review object.

**Comment by zhx828** [comment]
@victoria34 it's really difficult to compare the difference. Is there a way to only show the changed part? And I don't think showing _uuid should be the default. The curators should not care about this info.

**Comment by victoria34** [comment]
Sure, I'll try to figure it out.
