### ISSUE TITLE
For trial matching: the alternative allele rule should not be applied

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1699]

**Comment by victoria34** [comment]
Hi @zhx828, I checked the code and the alternative allele is removed from result.

https://github.com/oncokb/oncokb/blob/fb0429f2703ac33ddcd0e906bbdd0a7c1d1f026b/web/src/main/java/org/mskcc/cbio/oncokb/api/pvt/PrivateUtilsApiController.java#L268
