### ISSUE TITLE
Adding Variants in the OncoKB interface that are already in the VUS  section

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#175]
Right now, the system allows you to add a variant in an OncoKB gene page that is already listed as a VUS. There is no warning/nothing to indicate this variant already exists as a VUS. This leads to variants being duplicated in the curated section and the VUS section of a gene page. The system should 1) give a warning that this variant exists as a VUS and 2) not allow you to add the variant until the VUS is deleted.

**Comment by zhx828** [comment]
Duplicate issue of https://github.com/oncokb/oncokb/issues/439
