### ISSUE TITLE
Bar chart legend issue

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1786]
Both x/y axises are trimmed off...
 
https://beta.oncokb.org/gene/PBRM1
![Screen Shot 2019-10-30 at 4 53 55 PM](https://user-images.githubusercontent.com/5400599/67898010-de202d80-fb35-11e9-9dc9-258d9fef4252.png)

**Comment by victoria34** [comment]
Fix 
<img width="525" alt="Screen Shot 2019-10-31 at 5 16 54 PM" src="https://user-images.githubusercontent.com/14971266/67986798-3c1a4700-fc02-11e9-8a7d-c4c562730483.png">
