### ISSUE TITLE
Mapping to incorrect arm

### ISSUE THREAD

**Issue by ritikakundra** [oncokb/oncokb#1798]
"no alteration in BRAF defined by trial" - BRAF V600E pt matched to the arm that specifies no V600 mutation (should not matcg to IIIC, should map to IIA and IIB)

**Comment by victoria34** [comment]
Trial ID: NCT03091257
Patient Link: https://cbioportal.mskcc.org/patient/trialMatchTab?caseId=P-0035049&studyId=mskimpact#navCaseIds=mskimpact:P-0038789,mskimpact:P-0026126,mskimpact:P-0014286,mskimpact:P-0019291,mskimpact:P-0038785,mskimpact:P-0032419,mskimpact:P-0044241,mskimpact:P-0036653,mskimpact:P-0035047,mskimpact:P-0019884,mskimpact:P-0041045,mskimpact:P-0035049,mskimpact:P-0043494,mskimpact:P-0011359
