### ISSUE TITLE
Incorrect mapping

### ISSUE THREAD

**Issue by ritikakundra** [oncokb/oncokb#1799]
Wrong genomic criteria are matching. The fusion is matching to incorrect genomic criteria:
<img width="428" alt="Screen Shot 2019-10-29 at 4 25 19 PM" src="https://user-images.githubusercontent.com/12007862/67806269-ebbbb180-fa68-11e9-8440-b1086a451029.png">

**Comment by victoria34** [comment]
Hi @zhx828, could you also take a look of this issue? I tried that in Postman. The API does match those alterations.

![image](https://user-images.githubusercontent.com/14971266/68143700-01fdbd80-ff00-11e9-96b0-23f2f263d174.png)


API : ....../match/variant
Input: 
```
{
  "oncokbVariants": [
    {
      "alteration": "Fusions",
      "hugoSymbol": "BRAF"
    },
    {
      "alteration": "T599TT",
      "hugoSymbol": "BRAF"
    },
    {
      "alteration": "N486_T491delinsK",
      "hugoSymbol": "BRAF"
    },
    {
      "alteration": "K601T",
      "hugoSymbol": "BRAF"
    },
    {
      "alteration": "T599TS",
      "hugoSymbol": "BRAF"
    },
    {
      "alteration": "Kinase Domain Duplication",
      "hugoSymbol": "BRAF"
    }
  ],
  "queries": [
    {
      "alteration": "BRAF-MKRN1 fusion",
      "hugoSymbol": "BRAF",
      "id": "P-0016986-T01-IM6"
    }
  ]
}
```
