### ISSUE TITLE
There are no clinical trials for the patients in this link

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1863]
Please give as much information as possible before submitting your issue - Thank you

Issue: There are no clinical trials for the patients in this link, but they should be matched to the trial in question

Example: This patient should match just based on the tumor type

Screenshot:
![Screen Shot 2019-12-16 at 5 05 09 PM](https://user-images.githubusercontent.com/17145625/70947011-3d72c800-2026-11ea-9adf-fff28cbce2a5.png)

**Comment by victoria34** [comment]
@phillis2 Could you give me the trial ID? I can take a look into it.

**Comment by victoria34** [comment]
This is not an issue. The trial NCT02631044 doesn't match to the patient.

**Comment by phillis2** [comment]
@victoria34 - it doesn't seem like this trial matches to any patients...why does the link show patients that do not match?
