### ISSUE TITLE
If patient only has 1 sample, I don't think we need to include the "Matched Samples" line

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1864]
Please give as much information as possible before submitting your issue - Thank you

Issue: If the patient only has 1 sample, I don't think we need to include the "Matched Samples" line
![Screen Shot 2019-12-16 at 5 23 10 PM](https://user-images.githubusercontent.com/17145625/70948117-c0951d80-2028-11ea-8111-8e5beacb390f.png)

Example:

Screenshot:

**Comment by victoria34** [comment]
@phillis2 Well, I can remove that line easily for 1 sample case but I worried users may feel confused about that. You know, we show drug icon if a trial has drugs and hide it if a trial doesn't have any drugs. In this way, if `Matched Sample` line disappears, users may misread no samples matched to the trial. That's not what we want.

**Comment by phillis2** [comment]
I see - ok we can keep for now
