### ISSUE TITLE
IE 11 cannot see the icon

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1885]
For instance, in the cancer genes page, all icons are not shown on the page. https://www.oncokb.org/cancerGenes

**Comment by victoria34** [comment]
@zhx828 Could you double check that? I can see all icons on my pc.

![Screen Shot 2020-02-27 at 7 20 59 PM](https://user-images.githubusercontent.com/14971266/75498906-7a4c2b00-5996-11ea-8d8b-318969eedbc8.png)
