### ISSUE TITLE
This trial is missing drug and arm info

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1890]
Please give as much information as possible before submitting your issue - Thank you

Issue: 
This trial is missing drug and arm info
Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/71998316-62b1bb00-320d-11ea-89d6-f0a31803ab11.png)

**Comment by victoria34** [comment]
I think the trial data NCT02768766 is weird. We need to discuss about it.
