### ISSUE TITLE
For Trial NCT03505710, it does not seem to be matching to patients with ERBB2 amplified lung cancer

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1892]
Please give as much information as possible before submitting your issue - Thank you

Issue: This patient also has ERBB2 amplification, so I am unsure why that arm of the trial is not matching to this paitent

Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/72001165-d0acb100-3212-11ea-8d20-abc72fb2e894.png)
![image](https://user-images.githubusercontent.com/17145625/72001217-f5a12400-3212-11ea-8479-0e57b0105278.png)

**Comment by victoria34** [comment]
We do not map amplification to oncogenic mutation.
