### ISSUE TITLE
When an alteration (like AMP) is specified in a gene and all other mutations in that gene are restricted (like not ERBB2 Oncogenic mutations), the display should read...

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1898]
Please give as much information as possible before submitting your issue - Thank you

Issue: When an alteration (like AMP) is specified in a gene as an inclusion criteria and all other mutations in that gene are restricted (like not (!) ERBB2 Oncogenic mutations), the display should only read...ERBB2 Amplification. I don't think we should say "negative for alterations in ERBB2" because that is not true since we are including amplification. Since everytime we have amplification as an inclusion criteria, we need to curate not oncogenic mutations and amplification, I think the display on the portal should always just say Gene_Amplification (and leave out "negative for alterations in Gene"

Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/72185298-781b1680-33c0-11ea-9e83-dd65a8e03105.png)
![image](https://user-images.githubusercontent.com/17145625/72185309-7fdabb00-33c0-11ea-967e-abc1f514ae96.png)
![image](https://user-images.githubusercontent.com/17145625/72185316-85d09c00-33c0-11ea-9f0d-3cfc6b9ada64.png)

**Comment by victoria34** [comment]
The matched result is correct, but the language in patient view is not clear. It should be like `Negative for ERBB2 Oncogenic Mutations`.
