### ISSUE TITLE
The language here is misleading/not correct

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1900]
Please give as much information as possible before submitting your issue - Thank you

Issue: This patient mapped to the wrong arm of the trial - arm 3C - where it is mapped is for patients without BRAF V600E and this patient has BRAF V600E. Also, when we curate BRAF Oncogenic mutations and not BRAF V600 - the display should read: BRAF Oncogenic Mutations excluding V600

Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/72295581-e0b6fd00-3625-11ea-9617-2e0a791c2ebc.png)

**Comment by victoria34** [comment]
Have same problem:
https://github.com/oncokb/oncokb/issues/1898
https://github.com/oncokb/oncokb/issues/1903

**Comment by victoria34** [comment]
Correct negative language like the screenshot below:
![Screen Shot 2020-04-07 at 9 03 46 PM](https://user-images.githubusercontent.com/14971266/78733447-7c00fb00-7913-11ea-99f2-9edb68fee2fe.png)
