### ISSUE TITLE
This patient matches to trials but shows that there is no mutation testing

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1901]
Please give as much information as possible before submitting your issue - Thank you

Issue: 
This patient matches to trials but shows that there is no mutation testing - so I am not sure how the patient is matching
Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/72297728-810f2080-362a-11ea-8850-31e3ff73d5a3.png)
![image](https://user-images.githubusercontent.com/17145625/72297734-879d9800-362a-11ea-8811-682a26b6f724.png)

**Comment by victoria34** [comment]
I think that's because those 2 trials are matched by wildtype.
