### ISSUE TITLE
Not sure why this patient with an IDH1 mutation is not matching to NCT03220646

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1902]
Please give as much information as possible before submitting your issue - Thank you

Issue: The trial specifies brain cancer with oncogenic IDH! or IDH2 mutations, so why is this patient not matching? I don't think anything in the second arm of the trial is matching..

Example:

Screenshot:
![image](https://user-images.githubusercontent.com/17145625/72298057-448ff480-362b-11ea-9790-71d68170cbc2.png)
![image](https://user-images.githubusercontent.com/17145625/72298088-51ace380-362b-11ea-9340-8ae93f3a6001.png)

**Comment by victoria34** [comment]
@zhx828 You can see the trial has a clinical node with `CNS/Brain Cancer, NOS, >=18` but match-engine doesn't support tissue matching now.
