### ISSUE TITLE
add Only checkbox for variant

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#1903]
Please give as much information as possible before submitting your issue - Thank you

Issue: 
https://cbioportal.mskcc.org/patient/trialMatchTab?sampleId=P-0005428-T01-IM5&studyId=mskimpact
Example:

Screenshot:

**Comment by phillis2** [comment]
https://cbioportal.mskcc.org/patient/trialMatchTab?sampleId=P-0000755-T01-IM3&studyId=mskimpact

When you refresh, make sure this pt matches to trial for AR

**Comment by victoria34** [comment]
We don't need to add any checkboxes. The matched result is correct, but the language in patient view is not clear. It should be like `Negative for AR F877L and L702H`.
