### ISSUE TITLE
API beginner's doc

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#1912]
Beside the current API swagger page, it would be useful to have an API Doc page to explain use it.

- [ ] swagger code-gen
- [x] API get examples
- [x] Curl examples
- [ ] Python examples
- [x] OncoKB Annotator

**Comment by jjgao** [comment]
Could be something like https://docs.genomenexus.org/api with more info.

**Comment by victoria34** [comment]
OncoKB Gitbook: https://oncokb.gitbook.io/oncokb/

**Comment by zhx828** [comment]
We should have this documentation on api.oncokb.org
Also include the sections to describe different instances

**Comment by zhx828** [comment]
The API document is released under api.oncokb.org
