### ISSUE TITLE
Allow user to annotate biological information without registering

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1975]
The endpoint should not be authenticated, the following information should be provided.
gene exists,
variant exists,
oncogenicity,
mutationEffect

**Comment by zhx828** [comment]
We decided to set up a public instance without authentication.

**Comment by inodb** [comment]
@zhx828 what is the extra information you get when you do register?

**Comment by inodb** [comment]
Ah never mind, explained here: https://docs.cbioportal.org/2.4-integration-with-other-webservices/oncokb-data-access. The therapeutic information
