### ISSUE TITLE
Add `Resend Verification Link` email

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2090]
- [x] When user is registered by didn't receive the verification email
- [x] When user's account is expired

**Comment by zhx828** [comment]
@jjgao If user chooses to resend the verification email, the request will go through an API. I'm wondering whether I should delay the response just in case someone abuses this API? Like, they figure it out someone registered by not activated, so they could send a lots of emails by using this endpoint. Any thoughts? Am I overthinking it?

**Comment by zhx828** [comment]
What if we automatically resend the verification email again when they try to login? @jjgao

**Comment by jjgao** [comment]
> @jjgao If user chooses to resend the verification email, the request will go through an API. I'm wondering whether I should delay the response just in case someone abuses this API? Like, they figure it out someone registered by not activated, so they could send a lots of emails by using this endpoint. Any thoughts? Am I overthinking it?

I don't know if we need to worry about that. They could simply email that user :)

Anyway, I think it may be a good idea to add a recaptcha...
