### ISSUE TITLE
Move the stats for an separate database

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2178]
This is probably better to put into a NoSQL database.

- include the counts for oncokb annotated gene
- include the counts for oncokb annotated variants
- include the info about api requests

@jjgao @Leowisd  any database suggestion? Thinking to go with mongo or firebase.

**Comment by Leowisd** [comment]
I have not used firebase so I'm not familiar with it. But Mongo is good.

**Comment by jjgao** [comment]
I am wondering if there are any open source user track software we can use?
