### ISSUE TITLE
Updates to Clinical Trials Matching API

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2209]
- [x] Merge the following three to one endpoint /trials. And add two request parameters oncoTreeCode (required) and treatment (optional)
- /trials
- /trials/{tumorCode}
- /trials/{tumorCode}/{treatment}

I don't think we need to return all results using /trials.

- [x] Change the description of `/trials/cancerTypes` to `Return a list of trials using OncoTree Cancer Type`

- [x] let's just call the docker image as clinical-trial-matching. Change the version to 0.0.1 for now.

**Comment by Leowisd** [comment]
https://github.com/Leowisd/Clinical-trials-matching-production
