### ISSUE TITLE
CT Card updates

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2243]
- [x] lower case the drug name in the sentence `clinical trials of dabrafenib in melanoma: ** trials`

- [x] make icon a bit smaller

- [x] only show active trials

- [x] ~~Create a separate column for oncokb~~

**Comment by Leowisd** [comment]
![image](https://user-images.githubusercontent.com/32425638/94491274-88249180-01ad-11eb-8ce5-e0f1bdc5a468.png)
