### ISSUE TITLE
Combine GET/POST usage together in the usage analysis

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2303]
- [x] For the GET method, the usage_count in the token_stats table should always be 1, but the POST method has different usage. When combining together, the number from usage_count should be reflected on the final number.

- [x] Can we hide the usage of /api/private by default and add an checkbox to show/hide the usage?

**Comment by zhx828** [comment]
@Leowisd for the second point, I think it would be only useful under the page /admin/usage-analysis. No need to add for the User Information page.

**Comment by Leowisd** [comment]
@zhx828 There are two types of usage under /admin/usage-analysis, users based and resources based. Do we need to make the second point useful under both of them or just users-based?

**Comment by zhx828** [comment]
> @zhx828 There are two types of usage under /admin/usage-analysis, users based and resources based. Do we need to make the second point useful under both of them or just users-based?

Let's do both.

**Comment by Leowisd** [comment]
> > @zhx828 There are two types of usage under /admin/usage-analysis, users based and resources based. Do we need to make the second point useful under both of them or just users-based?
> 
> Let's do both.

Sure. And if we do both, I think maybe we could also just add it to user information page, since the components we used for resources-based and user information page are the same one.

**Comment by zhx828** [comment]
> > > @zhx828 There are two types of usage under /admin/usage-analysis, users based and resources based. Do we need to make the second point useful under both of them or just users-based?
> > 
> > 
> > Let's do both.
> 
> Sure. And if we do both, I think maybe we could also just add it to user information page, since the components we used for resources-based and user information page are the same one.

Ah I see, sure. But could you show the private by default in the user information page instead?

**Comment by Leowisd** [comment]
> > > > @zhx828 There are two types of usage under /admin/usage-analysis, users based and resources based. Do we need to make the second point useful under both of them or just users-based?
> > > 
> > > 
> > > Let's do both.
> > 
> > 
> > Sure. And if we do both, I think maybe we could also just add it to user information page, since the components we used for resources-based and user information page are the same one.
> 
> Ah I see, sure. But could you show the private by default in the user information page instead?

Sure.
