### ISSUE TITLE
Migrate database to AWS Aurora

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2356]
We've been sharing the database with portal team which works really well in the past few years. But in the recent development, there are some instabilities causing oncokb crash. We should move our data out of portal database so that we can isolate the issue. This could also prevent oncokb crush causing portal crushes.

We should also use this opportunities to evaluate how much resource we need and what''s the monthly payment for cloud computing.

**Comment by jjgao** [comment]
Good idea to have a separate db instance.

**Comment by zhx828** [comment]
We need a large instance which quite costly. This will happen when we move to MSK cloud.
