### ISSUE TITLE
Initiate the curation platform refactoring project

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2411]
We should use a react app generator. Some of the options available:

- [x] https://github.com/facebook/create-react-app#creating-an-app

- [x] https://github.com/temilaj/react-webpack-starter

- [x] https://github.com/mobxjs/mobx-react-boilerplate (take a look https://github.com/mobxjs/awesome-mobx)

- [x] We could also use jhipster, but not recommended https://www.jhipster.tech/2020/12/21/jhipster-release-7.0.0-beta.0.html

- [ ] Try to use jhipster generate front-end only project, try to modify react-mobx bluepoint

- https://www.jhipster.tech/separating-front-end-and-api/
- https://www.jhipster.tech/modules/marketplace/#/details/generator-jhipster-react-mobx

**Comment by Leowisd** [comment]
https://github.com/oncokb/curation-platform-refactoring
