### ISSUE TITLE
improve efficiency

### ISSUE THREAD

**Issue by Leowisd** [oncokb/oncokb#2497]
- [x] Separate sites info into another mapping file to decrease the size of trials mapping file

- [x] Store ID of trial instead of trial itself in mapping result file

- [x] Compress the mapping file to decrease the size

- [x] Create Gzip utils to process decompress 

- [x] Cache mapping result, sites and matched trials

- [x] Setup cronjob to update cache

**Comment by zhx828** [comment]
The issue is fixed https://github.com/oncokb/oncokb-pipeline/pull/12
