### ISSUE TITLE
Prepare the MM trial matching slides

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2506]
The slide should include the following points:

- [x] The current status of MM Trial integration from UHN and MSK

- [x] Challenges: merge trial info with the portal mongodb

- [x] Discuss the next step for the matching, ask for guidance from the community

- [x] Discuss the current status of MM, how to upgrade from v1 to v2

**Comment by jagnathan** [comment]
Identify amount of information to show in Results view vs Patient view; Annotation vs Tab.
