### ISSUE TITLE
incorrect API variant matching =

### ISSUE THREAD

**Issue by DavidTamborero** [oncokb/oncokb#2597]
Issue: It seems that some of the info returned by the OncoKB API is not matching correctly the queried variant
(or I may be missing some point in the matching logics)?

Example: When querying BRAF V600K, the API returns Dx info which (I belive) is specific of BRAF V600E

>query:
https://www.oncokb.org/api/v1/annotate/mutations/byProteinChange?hugoSymbol=BRAF&alteration=V600K&referenceGenome=GRCh37

> response (see asterisk):

{
  "query": {
    "id": null,
    "referenceGenome": "GRCh37",
    "type": "regular",
    "hugoSymbol": "BRAF",
    "entrezGeneId": 673,
    "alteration": "V600K",
    (...)

  },
  "geneExist": true,
  "variantExist": true,
  "alleleExist": true,
  "oncogenic": "Oncogenic",
  (...)
  "diagnosticImplications": [
    {
      "levelOfEvidence": "LEVEL_Dx3",
      "alterations": [
        "V600E" *********
      ],
      "tumorType": {
        "id": null,
        "code": "ECD",
        "color": "LightSalmon",
        "name": "Erdheim-Chester Disease",
       (.....)

**Comment by zhx828** [comment]
@DavidTamborero this indeed seems to be a bug. I will schedule a fix. https://www.oncokb.org/gene/BRAF/V600L
