### ISSUE TITLE
Genomic Change annotation error

### ISSUE THREAD

**Issue by oncokbdev** [oncokb/oncokb#2619]
SEVERE: Servlet.service() for servlet [publicApiV1] in context with path [] threw exception [Request processing failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: 2] with root cause
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.substring(String.java:1963)
	at org.mskcc.cbio.oncokb.genomenexus.VEPDetailedEnrichmentService.resolveHgvspShortFromAAs(VEPDetailedEnrichmentService.java:118)

**Comment by zhx828** [comment]
Need an example to reproduce the issue. We can try to annotate msk_impact_2017 study mutations. But need to construct the genomic change and hgvs query.

**Comment by zhx828** [comment]
The issue should be fixed in https://github.com/oncokb/oncokb/pull/2668
