### ISSUE TITLE
Define second scoring for the keywords relevant search

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2843]
Using the keyword library provided by Moriah (with perhaps others to come) - develop this search for keywords in such a way that the articles returning the highest "functional" score can be placed upwards in the results so that curators can most likely get to the articles of relevance.  Right now, I can get the counts for how many times the keyword term appears if multiple articles have the terms and it's too broad, on the other hand, if the number of times appears to be less relevant we can score by a simple 0 or 1 (not present / present) for each keyword and the highest scoring (summed) ones would then be the ones simply with presence for all of these keyword terms which would mean it is likely to contain a lot more functional information about the gene alteration.  

Clustering on too many terms might be difficult but looking at where the gene alterations words appear in relation to the keyword terms could be another step after reporting this with the simpler approach with code I've been developing to "post-process" the Tier1/Tier2 articles to get a sense of the timing involved.

**Comment by lukeczapla** [comment]
Okay, so I have worked it into Solr to return the termfreq (count) of the words too now.  The trickiest one is "cell line" where it's two terms (a phrase) but I found option debugQuery=true and it outputs it even for the phrases.  So preliminary data only assigned a 0 or 1 for each keyword (or keyword root/stem) for absent/present, and some articles could cheat this if it has a supporting document also matching, this is easily turned off with "-pmid_supporting:*" at the end of the query, though.  So the option is to give a score of 11 if the keyword is mentioned 11 times, as to strengthen the importance value, for example, PMID 34108213 has 11 mentions of express/ed/ion but we'll need a few others just to browse around and see when it does help and when it doesn't help, and there could be a limit too just like before, that maximum points could be 10 for any count 10 or above.  But I ran my tests on BRAF G469A, D594G, and T599I so far and the timing suggests while it couldn't be done in "real time" (it still should be run and stored in the Variants table), it is much faster and the 199 articles could be scored with the 5 keywords given so far in 2-3 seconds, so it is orders of magnitude quicker than curation to re-run very quickly upon adding more keywords.

**Comment by lukeczapla** [comment]
In the meantime, I'll leave a boolean flag for including supporting texts or not, and run it through the quickest version here which just tells it to look at the PMIDs of interest.  The 0/1 version for each keyword is already implemented, so that can be a boolean flag too and then there's a count-based score (which could then have a maximum score per keyword) and absent/present 0/1 score.

**Comment by lukeczapla** [comment]
31533235, 18077425, and 18794803 will be checked as they had scores >20 vs. other articles with lower values, and a few others had scores of ~15 too.
