### ISSUE TITLE
Article matching issues

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2907]
- [x] https://aimlcoe.mskcc.org/knowledge/getPDF/19376813.pdf?terms=BRAF,A246P,$KEYWORDS `zebrafish` in the title is identified as gene `braf`
- [ ] Alteration only in table, it should not be a high score match BRAF A246P https://aimlcoe.mskcc.org/knowledge/getPDF/19376813.pdf?terms=BRAF,A246P,$KEYWORDS (maybe put into category `Alteration only in table/figure`)
- [ ] Alteration only in figure, it should not be a high score match BRAF A246P https://aimlcoe.mskcc.org/knowledge/getPDF/20648242.pdf?terms=BRAF,A246P,$KEYWORDS (maybe put into category `Alteration only in table/figure`)
- [ ] ~No need to highlight References~ it's difficult to identify the section and highlight at the same time. The highlight takes a different approach. Not worth the time looking into just yet.
- [ ] The functional keyword score is off https://aimlcoe.mskcc.org/knowledge/getPDF/22798288.pdf?terms=BRAF,L597,$KEYWORDS this article has 7 mentions but the score is f=2 
- [x] https://aimlcoe.mskcc.org/knowledge/getPDF/25544599.pdf?terms=L597,$KEYWORDS this link uses different colors for alteration and keywords. I guess it's because I manually removed the gene in the url?
- [x] allow specify highlight color(hex code) in the url, for instance https://aimlcoe.mskcc.org/knowledge/getPDF/25544599.pdf?terms=L597:ffffff,$KEYWORDS

**Comment by lukeczapla** [comment]
Great, so okay right now the order the terms comes in determines the default colors you get (and you found that cool "," thing too to put nothing in a spot) - but now we can do $KEYWORDS:AAAAAA or BRAF:32A932 to override the color at that position.  We wrap around with 6 default colors right now, but most things don't have 6 colors.

So now I'm wrestling with all of these cases less from the highlighting but from the Table, Figure, etc. position, I think everything should be in a Section object with a title (even if it's the legend title like "Fig. 2") and text so this is the new pdf package (org.mskcc.knowledge.pdf) that is super easy to move into any other project in the future.  the use cases are tough so I will work with some of these ones above and PNAS is one of the very most challenging ones right now.
