### ISSUE TITLE
Login using Google credential

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2943]

**Comment by calvinlu3** [comment]
Progress
- [x] Generate using jhipster with keycloak setup
- [x] Setup google oauth with keycloak
  - Currently using docker to run keycloak (using h2 db by default, so data is not persisted)
  - [ ] Setup keycloak server with a sql db
- [ ] Verify that the user logging is authorized by checking the user table
- [ ] Setup admin user details page to add new users to backend user table and keycloak user list
