### ISSUE TITLE
Alteration specific PMIDs not being pulled for alternate alleles

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#297]
Please give as much information as possible before submitting your issue - Thank you

Issue: Alteration specific PMIDs are not getting pulled for missense mutations in TSC2

Example:https://cbioportal.mskcc.org/index.do?session_id=5863ee7011d2c4ebd89da177&show_samples=false&

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17145213/21527106/d9e41134-ccf6-11e6-93ac-30b1c4e113f4.png)
![image](https://cloud.githubusercontent.com/assets/17145213/21527116/e3954f68-ccf6-11e6-9c1a-986368d52bb0.png)

**Comment by schultzn** [comment]
The information for R1200W should show up in the Biological Effect tab for R1200Q - currently, that tab is not clickable. I think we should implement this functionality for alternate alleles.
