### ISSUE TITLE
Show new score together with the old score on the webpage

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2981]
- Sort by new score

**Comment by lukeczapla** [comment]
It is completed and deployed on aimlcoe server - so now we can address the Table issue more carefully in two ways (for scoring an reference to an alteration within tables):

1) It's either in the table itself
2) It's in the legend of the table

[3) If it's in the legend/text of a figure (?)]

So both cases are just covered by my [table = true] field for a Section object (Figures also have headers starting with Fig/Figure] at the /textArticle/{PMID} endpoint for new PDF parser, so this will help complete the other open issues as well
