### ISSUE TITLE
Deploy curation website to production cluster

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3072]
- [x] to be finished by Hongxin: we will add a readme in the DevOps pipeline on how to add a new subdomain.
- [x] deploy the oncokb-transcript: branch article-screening to curation.oncokb.org
   - [x] create subdomain curation.oncokb.org
   - [x] setup read/write permissions for oncokb_keycloak and oncokb_curation databases
   - [x] deploy keycloak
       - [x] Setup keycloak.oncokb.org subdomain
       - [x] Move https://github.com/calvinlu3/oncokb-keycloak-helm to oncokb repository
   - [x] deploy elasticsearch
   - [x] redis (https://docs.spring.io/spring-session/reference/guides/boot-redis.html)
   - [x] rename `article-screening` branch to `rc`

**Comment by calvinlu3** [comment]
Update: 
-  Deployed app but had to temporarily install another redis instance for spring session
   -  The error message I get when connecting with existing redis instance is: `ERR unknown command 'CONFIG', with args beginning with: 'GET', 'notify-keyspace-events',`
 - Need to update the keycloak custom theme to replace contact placeholder text to actual contact info
