### ISSUE TITLE
Parse Y1003mut properly

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3133]
Traditionally, we support 1003_1004mut. But Y1003mut is never supported. We should at least assign consequence to any?

**Comment by lukeczapla** [comment]
What is the nature of Y1003mut?  I had seen V600 as like a generic term for every possible mutation at that spot (basically, V600 alone in the text or V600A, V600C, V600D, ...), and then implemented a "?" operator ("V600?") for searching for anything that involved V600 followed by anything at all. It's all semantics and nomenclature when the curator has to make a call, so this link has it https://www.thno.org/v11/p4585/thnov11p4585s1.pdf but yet on Google it's mostly just links to OncoKB when you search for Y1003mut

**Comment by zhx828** [comment]
> What is the nature of Y1003mut? I had seen V600 as like a generic term for every possible mutation at that spot (basically, V600 alone in the text or V600A, V600C, V600D, ...), and then implemented a "?" operator ("V600?") for searching for anything that involved V600 followed by anything at all. It's all semantics and nomenclature when the curator has to make a call, so this link has it https://www.thno.org/v11/p4585/thnov11p4585s1.pdf but yet on Google it's mostly just links to OncoKB when you search for Y1003mut

@lukeczapla actually we only use V600 as positional variant for all missense mutations at position 600. We use mut to indicate on any.
