### ISSUE TITLE
Review feature related bugs and any other requests

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#315]
- [x] Update the red review statement 
- [x] Add level propagation in the review mode
- [x] Obsolete item will lead to deletion in database 
- [x] Migrate red hand items back
- [x] Save VUS
- [x] Save abstract
- [x] Remove additional info
- [x] Mutation name, tumor type name and treatment name is not traced by review mode. Tumor type name is stored under tumor.cancerTypes
- [x] Treatment index is incorrect passed when adding new treatment
- [x] Only display the items with change
- [x] Updated by name bug
- [x] Add trials to save all my changes
- [x] Move "Review Complete" button next to "Save all my changes" button
- [x] Save last reviewed content when click update gene button. (After deleting an item without confirm deleting in the database, click update gene button will still save it to database)

**Comment by JiaoJiao123** [comment]
Bugs
1: when the gene doc is in review mode, other admins is still able to edit it.

**Comment by JiaoJiao123** [comment]
- [ ] Update the red review statement 
- [ ] Add level propagation in the review mode
- [ ] Obsolete item will lead to deletion in database 
- [ ] Migrate red hand items back
- [ ] Save VUS
- [ ] Save abstract
- [ ] Save all updated items

**Comment by phillis2** [comment]
When a section needs review, can it be opened exactly to where the review is needed (where the red check mark is located?). This is so we do not need to click to open various tabs.

**Comment by zhx828** [comment]
@JiaoJiao123 could you check is there anything still undone from the list above? Thanks.
