### ISSUE TITLE
Look into Swagger XSS attack

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3240]
cBioPortal received an email from an user mentioning about the attack. https://groups.google.com/g/cbioportal/c/ZmHQU3J9KgE
I looked at our swagger, the url did pass to the backend but I don't see the alert showed in the post. Maybe the version we use already have the fix? We need to look into this issue. 

A relevant article https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers/

Portal did make a patch for it https://togithub.com/cBioPortal/cbioportal/pull/9768

**Comment by calvinlu3** [comment]
## Updates

I've tried passing the `configURL` parameter to our swagger page and I did not get any alerts. The [article](https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers/#:~:text=Another%20way%20of,between%20%3E%3D3.14.1%20%3C%203.38.0.) says that the package `swagger-ui-dist` versions `>=3.14.1 < 3.38.0` is vulnerable to the XSS attacks. We are using [swagger-ui-dist v4.1.3](https://github.com/oncokb/oncokb-public/blob/master/package.json#L162).

When I downgraded our version to `3.14.1` and go to the url `http://localhost:9095/swagger-ui/index.html?configUrl=https://jumpy-floor.surge.sh/test.json`, I am able to see the alert popup as described in the article.
![image](https://user-images.githubusercontent.com/59149377/191306285-467f15de-c135-40d8-bbcc-7e58a5d741ce.png)

Our version of swagger-ui is outside the vulnerable version range.
