### ISSUE TITLE
Redis cluster performance test

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3244]
I'd like to understand the performance differences between sentinel and redis cluster.
- [x] We can compare between sentinel with three pods(one leader, two followers) and three nodes redis cluster.
    - [x] First of all, use https://redis.io/docs/reference/optimization/benchmarks/ to test
    - [x] Test the following
- [ ] We should use whole genome sequencing data for testing annotation performance (using the byProteinChange endpoint). Ritika mentioned there are three studies in the portal are WGS studies. Let's use stad_oncosg_2018 study, you can download the mutation data by going to the link below and click on the download icon on the top of the page, next to the study header.
    - https://www.cbioportal.org/study/summary?id=pancan_pcawg_2020
    - https://www.cbioportal.org/study/summary?id=es_iocurie_2014
    - https://www.cbioportal.org/study/summary?id=stad_oncosg_2018
- [x] Test the following performance
    - [x] 500 variants per call
    - [x] 500 variants with 10/50/100 threads
- [x] Provide a document to show the current stats and good practice of using redis cluster

**Comment by calvinlu3** [comment]
Redis cluster performance test document: https://mskcc-my.sharepoint.com/:w:/g/personal/luc2_mskcc_org/ESiyRDBco-VDh5dyD1mwxxkBPyfRH2NottR6AQENUyteYA?email=zhangh2%40mskcc.org&e=r5BfX4
