### ISSUE TITLE
Performance test using oncokb-core on different AWS EC2 tiers

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3270]
The comparison is to find out which tier makes the most sense for our usage.
There tiers should be included in the comparison, T(general), C(compute optimized), R(memory optimized) tiers

Equivalent comparison:
t3a.xlarge: 4vCPU+16GB, $0.15/hour
c6a.xlarge: 4vCPU+8GB,  $0.15/hour
r6a.xlarge: 4vCPU+32GB,  $0.22/hour

@calvinlu3 r6a.xlarge seems using better cpu then t tier. if the performance is not significant, we probably could use r tier since it has a lot more memory.

**Comment by calvinlu3** [comment]
EC2 Instance Type | # variants | # core | max cpu | # threads | Average response
-- | -- | -- | -- | -- | --
c6a.xlarge | 100 | 4 | 4 | 2 | 3.7
c6a.xlarge | 100 | 4 | 4 | 4 | 5
c6a.xlarge | 100 | 4 | 4 | 8 | 10.2
  |   |   |   |   |  
t3a.xlarge | 100 | 4 | 4 | 2 | 7.7
t3a.xlarge | 100 | 4 | 4 | 4 | 12
t3a.xlarge | 100 | 4 | 4 | 8 | 25
  |   |   |   |   |  
r6i.xlarge | 100 | 4 | 4 | 2 | 3.3
r6i.xlarge | 100 | 4 | 4 | 4 | 4.7
r6i.xlarge | 100 | 4 | 4 | 8 | 9.3
