### ISSUE TITLE
Fine toning redisson connections

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3279]
The redisson creates a lot of connections with redis for one instance to keep the channel opens. It makes sense for application that only has one instance, but we are making plan to support tens/thousands instances. The default number of connections might not work in this setting.

**Comment by calvinlu3** [comment]
Redisson pub/sub connections:
- From Redisson wiki (https://github.com/redisson/redisson/wiki/2.-Configuration/#subscriptionconnectionpoolsize), a subscription connection is consumed when we use one of the objects. We do not use those, so we can decrease the number of connections Redis clients by setting `subscriptionConnectionMinimumIdleSize` and `subscriptionConnectionPoolSize` to zero.
- Redis pub/sub is useful when we want our services to observe real-time changes by subscribing to specific channels. We are not doing this.
