### ISSUE TITLE
Support service account

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3312]
In addition to user authentication through token, we should also support service account authentication.

I'm thinking the following
- treat service account(svc) the same as user account, but without ROLE_USER so it can not be used in the website
- the svc must associate with the company
- create company admin, ROLE_COMPANY_ADMIN
- company admin can create svc
- the svc needs a name(required, leave it in the first name field), password
- only company admin can modify svc account(password), this needs to be logged (optional: start with FIXED)
- create role ROLE_SVC, and replace ROLE_BOT
- create oncokb as a company and associate current bot to the company
- limit access for svc account. not all endpoints can be accessed
- Add SVC info in the account setting for company admin
- Add list of company admin in the account setting for company admin and ask them to reach out support@oncokb.org to add/remove the other admins

**Comment by zhx828** [comment]
More reading on k8s service account https://medium.com/@th3b3ginn3r/understanding-service-accounts-in-kubernetes-e9d2abe19df8

Some ideas to entertain and could be relevant
- We could create one service account for company by default
- company can create different service accounts with different names to monitor the usage
- service account tokens have long-lived token vs time bound token

**Comment by benzuzu** [comment]
We should add epic for adding account types, including web accounts and other logistical things. Regardless should be done after token format change.
