### ISSUE TITLE
Generate mockups on how to display descriptions on public website

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3328]
- [x] show mutation effect description in variant page
- [x] show mutation effect description  when hover over the reference icon in table
- [x] show treatment description when hover over the reference icon in table

**Comment by calvinlu3** [comment]
# Show mutation effect description in gene page table
### Option 1: Show description in table column
![image](https://user-images.githubusercontent.com/59149377/208472840-71544a4a-775d-493b-b536-22baebef33dd.png)

### Option 2: Show mutation effect description in tooltip
![image](https://user-images.githubusercontent.com/59149377/208526294-0fa83fd3-9875-4412-a407-ba0b8029be47.png)

## Preview of when you hover over references in description
![image](https://user-images.githubusercontent.com/59149377/208526362-50eacb5f-5848-4bb0-b7e0-34cdeabb4dd2.png)

<br></br>
<br></br>
# Show treatment description in tooltip

### Preview of treatment description in tooltip
![image](https://user-images.githubusercontent.com/59149377/208526149-ae060a68-c039-45d3-a3e4-5debe16ee209.png)

### Preview of missing information 
![image](https://user-images.githubusercontent.com/59149377/208526106-a5674b4d-9089-439f-9b45-d051e3151866.png)

### Preview of logged out version
![image](https://user-images.githubusercontent.com/59149377/208525033-d4533059-ab3d-47bc-b687-adf4f82f09dd.png)

<br></br>
<br></br>

# Show mutation effect description in variant page 
### Option 1: Show/Hide text (similar to gene background on gene page)
![image](https://user-images.githubusercontent.com/59149377/208531966-3d051016-9a5a-44e8-af70-bf11b2d35098.png)

### Option 2: Show mutation effect in dashed box 
There's too much whitespace on the left if the mutation effect description is long.

![image](https://user-images.githubusercontent.com/59149377/208537254-3ab86494-f9f2-4762-8b1e-b1081cb8c3d6.png)
