### ISSUE TITLE
Redis cluster IP address changes overtime

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3340]
What we noticed is that both cluster svc ip and also the node ip change. When the core registering the redis, it connects to all nodes using their ip. Once the ip changes, the core will throw SERVER error message and it will produce a 500 error code(potentially, still need to verify in https://github.com/oncokb/oncokb/issues/3330). The core is able to pick up the new ip very quickly.
- find out what causes the ip changes. Could it because the aws node is changed?
- find out if cluster ip changes, can we automatically update the redis-insight setting to use the latest ip
- verify the fix to https://github.com/oncokb/oncokb/issues/3330 will help with the ip shifting too

**Comment by calvinlu3** [comment]
Regarding second bullet point "find out if cluster ip changes, can we automatically update the redis-insight setting to use the latest ip":
- https://github.com/RedisInsight/RedisInsight/issues/1225
There is a feature request to have RedisInsight use the hostname instead of IPs

**Comment by zhx828** [comment]
The connection string was misconfigured in the redis insight which does not capture the latest IP addresses. We recently updated the string by using the headless string. It works fine now.
