### ISSUE TITLE
Add dedicated pages for Dx/Px levels

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3409]
We currently show Dx/Px levels in [Levels of Evidence page](https://www.oncokb.org/levels), but in dedicated tabs. To optimize search result in search engines, we'd like to create dedicated pages/url for dx and px(https://www.oncokb.org/diagnotisc-levels)

**Comment by SalihuDickson** [comment]
Hello @zhx82, I am currently working on this issue. But how will the dx and px pages be reached? will additional links need to be add to the nav bar or will the links be on the levels of evidence page
