### ISSUE TITLE
EGFR A289V mutation not being picked up as oncogenic even though its annotated 

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#341]
Issue: EGFR A289V mutation and hotspot not being picked up by OncoKB even though annotation exists

Example:https://cbioportal.mskcc.org/case.do?cancer_study_id=coadread_tcga_pub&sample_id=TCGA-AA-A00F-01

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17145213/22219576/493a04da-e179-11e6-8c15-34fcf25ad276.png)

**Comment by zhx828** [comment]
@debyani-chakravarty this sample does not have EGFR variant anymore, but I checked other samples with EGFR A289V https://cbioportal.mskcc.org/case.do?cancer_study_id=mskimpact&sample_id=P-0013580-T01-IM5 looks like we can pick up the annotation now. Could you double check for me? Thanks!

**Comment by debyani-chakravarty** [comment]
It works now, thank you!
