### ISSUE TITLE
Update components in the News page to include the links to annotation pages

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3410]

**Comment by Gazalshyam** [comment]
Hello @zhx828,
I'm interested in participating in the Google Summer of Code (GSoC) 2023 program and contributing to the Add gene-level charts to study view for categorical molecular profiles.

I'm interested in solving this issue, could you please tell me how to more about it?

**Comment by Gazalshyam** [comment]
@zhx828 is this issue still open

**Comment by zhx828** [comment]
> @zhx828 is this issue still open 

Sorry, the issue is taken

**Comment by Gazalshyam** [comment]
@zhx828 Could please suggest me with another issue that is still open

**Comment by zhx828** [comment]
> @zhx828 Could please suggest me with another issue that is still open

Which gsoc project would you like to do?

**Comment by Gazalshyam** [comment]
I would like to do Add gene level charts to study view for categorical molecular profiles.
https://github.com/cBioPortal/GSoC/issues/100
