### ISSUE TITLE
Unusual OncoKB account activities (data usage) email didn't sent out

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3413]
The webpage shows it sent out successfully, but I didn't see it in the Sent box.

**Comment by zhx828** [comment]
I tested locally, it works properly. I checked the production log which indicates the email sent properly, no exception thrown. But I don't see the email in the Sent box. I will just wait for few days to see whether user replies.

**Comment by calvinlu3** [comment]
Tested locally using oncokb dev email and a personal email. The email was found in the sent folder.

**Comment by zhx828** [comment]
@calvinlu3 thank you. Let's close this ticket for now.
