### ISSUE TITLE
Add gene/alteration pages linkout in the News page

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3414]
Few components in the News page should include a linkout to gene/alterations pages.

**Comment by chungwwei** [comment]
Hi @zhx828, I like to contribute to this issue.

Do you mean the `gene` column in some tables need to be linked to the gene page?

![image](https://user-images.githubusercontent.com/39935368/225701557-3f8b19ac-e1c4-4953-8d68-17db6d300a33.png)

With picture above as an example, clicking RET, TP53, and other items would linked to gene page with their `hugo`

**Comment by zhx828** [comment]
> Hi @zhx828, I like to contribute to this issue.
> 
> Do you mean the `gene` column in some tables need to be linked to the gene page?
> 
> ![image](https://user-images.githubusercontent.com/39935368/225701557-3f8b19ac-e1c4-4953-8d68-17db6d300a33.png)
> 
> With picture above as an example, clicking RET, TP53, and other items would linked to gene page with their `hugo`

@chungwwei Exactly. Gene column should link to gene page. Mutation column should link to alteration page using info from gene column and mutation column.

**Comment by zhx828** [comment]
@chungwwei for adding alteration link, here are some info you would need
- You would need to get both GENE and MUTATION info in order to use component AlterationPageLink
- Not every MUTATION can be linked to a page. Usually we tent to make News page more user readable but that causes difficulty to parse. What you can do for now is to include link for MUTATION when the string does not include `,|/` I can take a glance of the News page after updating to see whether we want to update our rules.
