### ISSUE TITLE
EGFR EL746IP is an exon 19 insertion

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#345]
EGFR EL746IP is an exon 19 insertion, is being picked up as oncogenic BUT the summary statement says its not investigated by OncoKB

Example: https://cbioportal.mskcc.org/case.do?cancer_study_id=mskimpact&sample_id=P-0014932-T01-IM6

![image](https://cloud.githubusercontent.com/assets/17145625/22352344/b101ec82-e3e9-11e6-893a-100f851d0a8c.png)

**Comment by zhx828** [comment]
EL746IP is exon mutation, not insertion. Currently not annotation for it.
