### ISSUE TITLE
Create a tech stack summary of CTIMS

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3474]
We should compare the libs used by the tool with [oncokb-transcript rc branch](https://github.com/oncokb/oncokb-transcript/tree/rc)

**Comment by scarrero4660** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-78d77dcd-7fff-e4d6-6cbe-693d25a89e99"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The CTIMS repository currently uses a Nx Next Nest as a monorepo framework. It also uses Prisma for server-side reading/writing to database, Jest and Cypress for testing purposes, as well as MySQL as a database, Docker, and Keycloak for authentication. As we are extracting frontend components, primarily the Next libraries will be relevant in oncokb-transcript.</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">If Keycloak is being used, Java 8 or higher is required, which is compatible with oncokb-transcript.</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CTIMS requires React and React-dom version 18.2.0 or higher while oncokb-transcript currently uses 17.0.1.&nbsp;</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Below is a chart of dev dependencies used in CTIMS that have a different version from those used in oncokb-transcript. Most conflicts below would require minor version updates.</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

Dependency | CTIMS version | oncokb-transcript version
-- | -- | --
@types/node | 16.11.7 | 16.9.1
@types/react | ^18.0.24 | 17.0.20
@types/react-dom | ^18.0.8 | 17.0.9
@typescript-eslint/eslint-plugin | ~5.10.0 | 4.31.1
@typescript-eslint-parser | ~5.10.0 | 4.31.1
eslint | ~8.7.0 | 7.32.0
eslint-config-prettier | 8.1.0 | 8.3.0
eslint-plugin-react | 7.27.0 | 7.25.1
jest | 27.2.3 | 27.2.0
prettier | ^2.5.1 | 2.4.0
sass | 1.43.2 | 1.39.2
typescript | ~4.5.2 | 4.4.3

</div></b>

**Comment by scarrero4660** [comment]
Below is a list of dependencies and dev dependencies used in CTIMS that would be added to oncokb-transcript

Dependencies added
"@ant-design/icons":"^4.5.0",
"@nestjs/common":"^9.4.0",
"@nestjs/core":"^9.4.0",
"@nestjs/mapped-types":"^1.2.2",
"@nestjs/passport":"^9.0.3",
"@nestjs/platform-express":"^9.4.0",
"@nestjs/swagger":"^6.3.0",
"@nrwl/next":"15.8.1",
"@prisma/client":"^4.5.0",
"@reduxjs/toolkit":"^1.9.1",
"@rjsf/antd":"^5.2.1",
"@rjsf/core":"^5.2.1",
"@rjsf/material-ui":"^5.2.1",
"@rjsf/utils":"^5.2.1",
"@rjsf/validator-ajv8":"^5.2.1",
"antd":"^4.12.3",
"clsx":"^1.2.1",
"core-js":"^3.6.5",
"dayjs":"^1.10.4",
"json-schema":"^0.4.0",
"jsonpath":"^1.1.1",
"jwt-decode":"^3.1.2",
"jwt-encode":"^1.0.1",
"keycloak-connect":"^21.1.0",
"next":"^13.0.0",
"next-auth":"^4.22.1",
"nx":"^15.8.1",
"passport":"^0.6.0",
"passport-keycloak-bearer":"^2.3.0",
"primeicons":"^6.0.1",
"primereact":"^8.7.3",
"react-json-view":"^1.21.3",
"react-redux":"^8.0.5",
"reflect-metadata":"^0.1.13",
"regenerator-runtime":"0.13.7",
"rxjs":"^7.0.0",
"tslib":"^2.0.0",
"uuid":"^9.0.0",
"yaml":"^2.2.1"

devDependencies added
"@nestjs/schematics":"^9.1.0",
"@nestjs/testing":"^9.4.0",
"@nrwl/cli":"15.8.1",
"@nrwl/cypress":"15.8.1",
"@nrwl/eslint-plugin-nx":"15.8.1",
"@nrwl/jest":"15.8.1",
"@nrwl/linter":"15.8.1",
"@nrwl/nest":"15.8.1",
"@nrwl/node":"15.8.1",
"@nrwl/react":"15.8.1",
"@nrwl/tao":"15.8.1",
"@nrwl/web":"15.8.1",
"@nrwl/workspace":"15.8.1",
"@tauri-apps/cli":"^1.2.3",
"@testing-library/react":"12.1.2",
"@testing-library/react-hooks":"7.0.2",
"@types/jest":"27.0.2",
"@types/jsonpath":"^0.2.0",
"@types/uuid":"^9.0.0",
"@types/yaml":"^1.9.7",
"babel-jest":"27.2.3",
"cypress":"^11.2.0",
"eslint":"~8.7.0",
"eslint-config-next":"12.0.7",
"eslint-plugin-cypress":"^2.10.3",
"eslint-plugin-import":"2.25.2",
"eslint-plugin-jsx-a11y":"6.5.1",
"eslint-plugin-react-hooks":"4.3.0",
"prisma":"^4.13.0",
"react-test-renderer":"17.0.2",
"ts-jest":"27.0.5"

**Comment by calvinlu3** [comment]
@zhx828 The rc branch was generated using jhipster v7.2.0. The reason is because we were using the `react-mobx` blueprint, which only supports up to 7.2.0. We would need to remove the mobx blueprint or upgrade the blueprint.
Related PR:
https://github.com/oncokb/oncokb-transcript/pull/42
