### ISSUE TITLE
an alternate allele (in vus section) is showing up as a known oncogenic mutation

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#348]
Please give as much information as possible before submitting your issue - Thank you

Issue: This is an alternate allele (in vus section); however in the portal it is showing up as a known oncogenic mutation - with the annotation for E709_T710delinsD	

Example: EGFR E709_T710delinsD	

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17145625/22481581/cfa9ff2a-e7c3-11e6-8c29-9333d0021bb0.png)

**Comment by zhx828** [comment]
In the new version, this will be treated as hotspot. Then it will show as Predicted oncogenic
