### ISSUE TITLE
Create InfoSection component for gene/alteration/ct/drug

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3534]
This component will be used to show the contents of each dropdown. Based on the type of the content, the color of the component should be reflected.

Example mockup:
![Image](https://user-images.githubusercontent.com/59149377/253017072-2d35c675-6c6f-46b0-bf8e-820518811782.png)

- [x] Make component expandable
- [x] Show summary statistics for each section
- [ ] Update breadcrumb based on the depth of the dropdown

**Comment by zhx828** [comment]
Issue fixed in https://github.com/oncokb/oncokb-transcript/pull/140
