### ISSUE TITLE
wrong level_3a

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#356]
http://dashi.cbio.mskcc.org:38080/internal/legacy-api/indicator.json?hugoSymbol=NRAS&alteration=Q61X&tumorType=not-a-cancer

**Comment by zhx828** [comment]
@jjgao  X should match any amino acid at this location? What's this not-a-cancer?

**Comment by jjgao** [comment]
@zhx828 strange. it was Level_3a.

The public site give the correct data: http://dashi.cbio.mskcc.org:38080/legacy-api/indicator.json?hugoSymbol=NRAS&alteration=Q61X&tumorType=not-a-cancer
