### ISSUE TITLE
Improve OncoKbTable component in oncokb-curation

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3564]
As generated by JHipster, the searching, sorting, and pagination are handle on each entity page. We should:
- [x] Move those logic and components into the `OncoKbTable` component. Currently, if we need a searchable/filterable/pageable table, we need to copy those components/functions into each page.
- [x] Support pagination given full dataset. This is useful when we want to display Firebase data (we fetch all).
   - [x] For entities, pagination/filtering/searching is done on the backend
   - [x] For firebase entities, we need to support it on the frontend in the `OncoKbTable` component

**Comment by zhx828** [comment]
We will downgrade react-table to v6 so we can use the same component as in oncokb-public.
We later will evaluate react-table v8 and ag-grid(MSK uses) for next step.
