### ISSUE TITLE
413 Request Entity Too Large on instance for MSK portal 

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3578]
Background:
cBioPortal has integration of OncoKB under the annotation column. It pulls the annotation in realtime. The following query sends a single POST request with 7K mutations in the body and OncoKB service returns 413 code.

This query https://cbioportal.mskcc.org/results/mutations?cancer_study_list=mskimpact&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cstructural_variants%2Ccna&case_set_id=mskimpact_cnaseq&gene_list=ATM&geneset_list=%20&tab_index=tab_visualize&Action=Submit includes 7K mutations. 

```[tasklist]
### Tasks
- [x] Find out where the threshold is defined. I assume this happened on the load balancer level.
- [x] Modify the threshold to allow 10K mutations.
```

**Comment by calvinlu3** [comment]
Here are the logs from ingress-nginx. 
```
2023/10/25 18:41:53 [error] 35#35: *183029930 client intended to send too large body: 1346490 bytes, client: 10.1.46.226, server: core.oncokb.aws.mskcc.org, request: "POST /api/v1/annotate/mutations/byProteinChange HTTP/1.1", host: "core.oncokb.aws.mskcc.org"
10.1.46.226 - - [25/Oct/2023:18:41:53 +0000] "POST /api/v1/annotate/mutations/byProteinChange HTTP/1.1" 413 176 "-" "Java/11.0.20.1" 299 0.112 [-] [
```

We can see that the error code returned is 413. Also, the size of the body is >1MB, which is the default max allowable body size by nginx. [Ref](https://docs.nginx.com/nginx-management-suite/acm/how-to/policies/request-body-size-limit/#:~:text=The%20Request%20Body%20Size%20Limit,error%20code%20will%20be%20returned.)

We should update this [file](https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/blob/master/oncokb/oncokb-msk/prod/ingress_oncokb_prod.yaml) to increase the body size.
- `nginx.ingress.kubernetes.io/proxy-body-size: 512m`

**Comment by calvinlu3** [comment]
fixed in https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/commit/1b714ff899eda2aa6ccba9a987c3c3ee64533bbe
