### ISSUE TITLE
Issues with alternate allele implementation

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#361]
-- TSC2 R1200Q - Alternate allele - marked correctly in the portal, but there is no way to get to the original PMID.
https://cbioportal.mskcc.org/index.do?session_id=5863ee7011d2c4ebd89da177&show_samples=false&

-- PIK3CA E542Q
https://cbioportal.mskcc.org/index.do?session_id=5873d56f11d2c4ebd89da3ec&show_samples=false&

-- BRAF N581I
https://cbioportal.mskcc.org/index.do?session_id=58a23e8d11d2c4ebd89db07e&show_samples=false&

**Comment by zhx828** [comment]
@debyani-chakravarty could you give me some more information what you mean by `there is no way to get to the original PMID.` ? Thanks!

**Comment by debyani-chakravarty** [comment]
It appears to be fixed. Basically for an alternate allele can we show the automated sentence (which you do) and the reference for the parent allele (which you also do)
