### ISSUE TITLE
Fix deleted mutation still appears in mutation list

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3655]

**Comment by calvinlu3** [comment]
Mutations that don't need to be reviewed are deleted immediately.

Originally, I created this ticket because mutation that need to be reviewed before deleting still appear in the list. 

When a mutation is pending deletion, should it still appear in the list on Curation Page?

**Comment by zhx828** [comment]
We need to indicate the mutation has been deleted. To start with we can the do following
- add a strikethrough on the mutation name
- change the border to `danger`
- remove all actions and stats
- remove the collapsible
