### ISSUE TITLE
Sort mutation list

### ISSUE THREAD

**Issue by bprize15** [oncokb/oncokb#3695]
Sort the mutation list in the following order:

1. Treatments first - sorted by highest levels of evidence for treatment
2. Single nucleotide - sorted by position
2. Special mutations
3. Rest

**Comment by bprize15** [comment]
Within each group, I have chosen to maintain the ordering from firebase.

**Comment by zhx828** [comment]
@bprize15 sorry I'm late on this ticket. But I would expect to sort the mutation by highest level, then oncogenicity, special oncogenic mutations, single mutation and rest. But let's double check with the curators tomorrow.
