### ISSUE TITLE
protein change url search with parenthesis does not work 

### ISSUE THREAD

**Issue by didiercroes** [oncokb/oncokb#3732]
I use a local istance cbioportal and import study in it.
The RNAseq  analysis report protein changes with parentheses which is concistent with recomendations as the protein itself as not been analysed. the protein change is imported with parentheses exemple :[(Y234*)
Issue:
in cbbioportal a link with the oncokb is created to link the suplementary information:
https://www.oncokb.org/gene/TP53/(Y234*) . This link return unknown in onkokb but if I remove the parenthese 
https://www.oncokb.org/gene/TP53/Y234* . The link retrun the information I expected.
Is it possible, as the parentheses are correct in the format is correct that oncokb ignores the parentheses?

Example:
https://www.oncokb.org/gene/TP53/(Y234*) . This link return unknown in onkokb but if I remove the parenthese 
https://www.oncokb.org/gene/TP53/Y234* . The link retrun the information I expected.

Screenshot:

**Comment by zhx828** [comment]
@didiercroes for `The RNAseq analysis report protein changes with parentheses which is concistent with recomendations` could you point me to the recommendation?

**Comment by didiercroes** [comment]
https://hgvs-nomenclature.org/stable/recommendations/protein/substitution/
in fact the parentheses means that "predicted consequences, i.e. without experimental evidence (no RNA or protein sequence analysed), should be given in parentheses, e.g., p.(Arg727Ser)."
I could remove the parenthese before loading into cbBioportal but I will loose the info. What do you think?

**Comment by zhx828** [comment]
> https://hgvs-nomenclature.org/stable/recommendations/protein/substitution/ in fact the parentheses means that "predicted consequences, i.e. without experimental evidence (no RNA or protein sequence analysed), should be given in parentheses, e.g., p.(Arg727Ser)." I could remove the parenthese before loading into cbBioportal but I will loose the info. What do you think?

@didiercroes this is certainly new to me. I can discuss internally about supporting it. But given we also use parenthesis within our format(for instance: Oncogenic Mutations (excluding E17K)), we would need time to implement. Before that, I think you have to trim the parenthesis before importing.

**Comment by didiercroes** [comment]
After discussion with the end users, I finally removed the parenthesis before importing the data in cbioportal.
so no emergency.
Also, it's maybe cbioportal who should remove the parenthèses in their link to oncoKB.
Thanks for the discussion.
