### ISSUE TITLE
Generate examples of genomic changes that are properly formatted

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3816]
Generate a list of of properly formatted genomic locations with different sequence type changes:
Deletion, Duplication, Insertion, Inversion, Deletion-Insertion, etc

We should be following the hgvs nomenclature (https://hgvs-nomenclature.org/stable/recommendations/DNA/substitution/)?

**Comment by leexgh** [comment]
Examples are added in Genome Nexus readme: https://github.com/genome-nexus/genome-nexus?tab=readme-ov-file#examples
