### ISSUE TITLE
Changing the propagation of a level from "3B" to "No level" does not appear in Review mode 

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#461]
Taselisib + Fulvestrant is 3A in Breast Cancer for PIK3CA Oncogenic Mutations and was getting propagated to 3B Colorectal cancer. I changed this in the curation interface. I was not asked for approval of this change in the Review mode

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17145213/24005570/bf125ace-0a3f-11e7-8bba-50aa9cf5cac7.png)

**Comment by zhx828** [comment]
@JiaoJiao123 please confirm this issue has been solved.
