### ISSUE TITLE
Review mode hangs when I click "Accept all my changes"

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#465]
Issue: I accepted all the changes made by other curators. I clicked "Accept all my changes" even though I hadn't made any. I guess this confuses the system and causes it to hang.

If I haven't made any changes, can the "Accept all my changes" button be greyed out or something? Then I will not click it and the system will not hang.

![image](https://cloud.githubusercontent.com/assets/17145213/24052712/d09348f8-0b0c-11e7-86c3-2a62e4506169.png)

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty Thank you for letting us know this issue. This should be solved by a software release coming soon. will keep you update.
