### ISSUE TITLE
In trying to un-obsolete an entry -- running into error message

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#482]
Issue: Under BCL2L11, I would like to un-obsolete the Deletion entry and I run into the following error message. 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17145213/24213331/7f3bf842-0f08-11e7-82b3-a05b896c96c4.png)

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty Thanks for letting us know. I will work on it.

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty This issue just get solved. will push out soon.
