### ISSUE TITLE
Accept all my changes is not working

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#483]
Please give as much information as possible before submitting your issue - Thank you

Issue:Not all my changes were automatically expanded. When I clicked "Accept all my changes" it showed that it accepted only ONE of my changes, but the unexpanded sections just reappeared. When I manually expanded them, the changes had not been accepted. When I clicked "Accept all my changes" after manually opening all the sections I encounter the following error:
![image](https://cloud.githubusercontent.com/assets/17145213/24213892/511e3900-0f0a-11e7-8ae4-728e0842de32.png)

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty Thanks for letting us know. I am looking into it.

**Comment by zhx828** [comment]
Issue has been solved in https://github.com/oncokb/oncokb/pull/484
