### ISSUE TITLE
TSC1 mutations in MSK-IMPACT cohort

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#490]
The tumor type summary refers to subependymal giant cell astrocytomas "While everolimus is considered standard care for the treatment of patients with subependymal giant cell astrocytomas harboring inactivating TSC1 or TSC2 alterations, its clinical utility in patients with TSC1 X121_splice altered glioma is unknown."
But the table has the Level-associated cancer type as Renal Cell Carcinoma

https://cbioportal.mskcc.org/index.do?cancer_study_list=mskimpact&cancer_study_id=mskimpact&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mskimpact_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=mskimpact_cna&data_priority=0&case_set_id=mskimpact_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TSC1%0D%0A%0D%0ASHQ1&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17145213/24273703/36d02702-0ffa-11e7-8bce-46a97708b8bd.png)

**Comment by zhx828** [comment]
It contains the same treatment Everolimus for both CNS Cancer and Renal Cell Carcinoma, but the script only pick up one of the evidence
