### ISSUE TITLE
I can't accept Ritika's change to NCCN guidelines

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#496]
Whenever I try to accept Ritika's update of the NCCN guidelines Version (from 2.2015 to 1.2016) the system hangs and the change is not accepted after I quit Review mode

![image](https://cloud.githubusercontent.com/assets/17145213/24378850/73df3384-1312-11e7-9e3a-01057a0e3100.png)

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty Thanks for letting us know. I will look into it.
