### ISSUE TITLE
Genes that need review disappear after reviewing a gene

### ISSUE THREAD

**Issue by MoriahNissan** [oncokb/oncokb#502]
Please give as much information as possible before submitting your issue - Thank you

Issue: after accepting changes in a gene and returning to the genes page, none of the genes will say they need review and I have to refresh my page in order to see which genes to review

Example: http://oncokb.org/curate/#/genes

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/20099031/24421138/33df2d50-13c3-11e7-9262-ec8d96d35760.png)

**Comment by JiaoJiao123** [comment]
@MoriahNissan This is solved. will push it out soon.

**Comment by zhx828** [comment]
@MoriahNissan @JiaoJiao123 I've updated the website. Please check whether this issue has been solved. Thanks.

**Comment by JiaoJiao123** [comment]
@zhx828 yep, I checked. and the fix is in.
