### ISSUE TITLE
Rejecting changes in Review Mode

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#535]
Issue: When in Review Mode if I reject the change to a description, there is no indication that the curation interface receives the "rejection" command. Also Since I don't accept the new Description of evidence, it would be nice if the curation interface restores Old Content. Basically if I reject a change in Review Mode it's the same as if I never reviewed it.

Example: PIK3R1 Summary of Biological Effect Descriptions of Evidence. The new curation is too abbreviated and I want to restore the old DofE. Nothing happens.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17145213/24681840/ea309746-1964-11e7-8fc9-87d2eadb903e.png)

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty sorry about this issue. I am fixing it.

**Comment by debyani-chakravarty** [comment]
Thank you JiaoJiao -- no apologies necessary!

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty This issue is fixed. You can reject items now. Could you check it out when you get a chance? Thanks!
