### ISSUE TITLE
curation queue

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#536]
It would be nice to add a curation queue in the gene curation page.

At the bottom of the page add a new section: `To curate` with a table of the follow columns.

 - PMID or Abstract (required)
 - Link (optional)
 - Variants (optional)
 - Added by whom and when (automatically populated)
 - Curated (check box)

**Comment by debyani-chakravarty** [comment]
- Screenshots (optional)

**Comment by JiaoJiao123** [comment]
It looks feasible, let's discuss it in detail later.
