### ISSUE TITLE
Failure for Review mode to update the database in TGFRB2

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#540]
There are three changes that were not updated. I refreshed the page but the same three data elements are not updated into the database in review mode:
![image](https://cloud.githubusercontent.com/assets/17145213/24727602/98de70dc-1a24-11e7-97a3-ca4e85a282de.png)

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty get it. I will look into it.

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty This is solved. Could you check it out when you get  a chance?

**Comment by debyani-chakravarty** [comment]
It worked -- thank you so much! This issue can be closed.
