### ISSUE TITLE
Clinical Report discrepancy

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#576]
AXL P444A is picked up as an oncogenic mutation even though in the realtime google docs, there is no annotation of AXL P444.

At 10.32 am CVR picked up from the OncoKB API that P444A is oncogenic. This is likely coming from an alternate allele because in cBioPortal P444S is ALSO indicated as oncogenic (see screenshot). 
![image](https://cloud.githubusercontent.com/assets/17145213/25295732/cf0b4d3e-26b2-11e7-8f8b-1cdebfa13743.png)
However the patient view of this sample DOES NOT have AXL P444S as oncogenic:
![image](https://cloud.githubusercontent.com/assets/17145213/25295773/02a9a6e0-26b3-11e7-9ff0-9fe980f5917f.png)
Either way annotation has nothing about P444 anything

**Comment by zhx828** [comment]
This is same issue of BRCA1. It has been solved.
