### ISSUE TITLE
Cursor keeps moving to the beginning of the text box

### ISSUE THREAD

**Issue by debyani-chakravarty** [oncokb/oncokb#589]
Cursor automatically moves to the beginning of the text box in Review mode.

**Comment by JiaoJiao123** [comment]
@debyani-chakravarty This has been solved

**Comment by zhx828** [comment]
@JiaoJiao123 I had a second thought last night about this issue. If the moment we open the page and if the driveRealtimeString is different, it will start to trigger reassigning the content data. That explains sometimes if I open a big gene, it freezes the page. We need to find a better way to do this.
