### ISSUE TITLE
VUS update issue

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#673]
Please give as much information as possible before submitting your issue - Thank you

Issue: 

Example:

Screenshot:

**Comment by zhx828** [comment]
@JiaoJiao123 I think it's because the curator didn't connect to the internal network. Just got another alert today

**Comment by JiaoJiao123** [comment]
Implement a feature as below in the backend to handle this.
Accumulate the cases that failed due to the internal network, send the email daily, instead of sending email each time it fails.
