### ISSUE TITLE
Some Drug Titles that are capitalized in OncoKB are lower case when we generate reports

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#68]
example: 

KRAS (Cobimetinib is capital in the annotation)

MEHD7945A + cobimetinib
Level of evidence: 4
MEHD7945 is a specific dual antibody that targets EGFR and ERBB3 (PMID: 22014573). A postulated mechanism of resistance to EGFR-monoclonal antibody treatment in colorectal (CRC), triple negative breast cancer (TNBC) and head and neck squamous cell carcinomas (HNSCC) is increased ERBB3 expression and consequent re-activation of EGFR-downstream signaling (PMID: 23172311, 22014573, 24667376). As monotherapy, MEHD7945A has shown promising activity in patients with HNSCC with a low toxicity profile (PMID: 26034219). Cobimetinib is a Genentech developed MEK-inhibitor that was recently FDA-approved in combination with vemurafenib for the treatment of metastatic melanoma (PMID: 25265494, 25037139). MEK inhibitors as monotherapy have not shown activity in patients with KRAS-mutant colorectal tumors or HNSCC (PMID: 22805291, 15483017). The limited activity of MEK inhibitors in RAS-mutant colorectal cancer may be due to release of ERK-dependent negative feedback on upstream receptors, such as EGFR and ERBB3, providing a rationale for combined MEK and HER receptor inhibition. It is also speculated that potent inhibition of the MAPK pathway (by blocking EGFR and downstream MEK using MEHD7945A and cobimetinib respectively) as well as ERBB3-downstream PI3K pathway (using MEHD7945A) represents a rationale combination therapy strategy.

**Comment by zhx828** [comment]
@phillis2 I believe this drug has been imported before with lower case. And database will treat 'Cobimetinib' and 'cobimetinib' as the same drug and it won't create a new record which makes sense because they are the same. But I need to find a way to deal with this issue. @jjgao any suggestion?
