### ISSUE TITLE
Combine PMIDs for Oncogenic and Mutation Effect

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#691]
Since we combined oncogenic and mutation effect section, Biological variants related api should also be updated, whose end point is 'search/variants/biological'. 

1) In the BiologicalVariant model, we need to combine together mutationEffectPmids and  oncogenicPmids, mutationEffectAbstracts and oncogenicAbstracts.
2) In the function 'getBiologicalVariants' from MainUtils, we change the way of setting BiologicalVariant pmids and articles correspondingly.

**Comment by JiaoJiao123** [comment]
@zhx828 When you complete this, I will update the gene page and variant page correspondingly.  If possible, could you please make the change in PR #681? So I don't have to combine two of your PRs to build war file. Thanks!

**Comment by zhx828** [comment]
@JiaoJiao123 this change may not just apply to biological variants endpoint. I would rather take a look all places where both oncogenic pmids and mutations pmids are present all together. Please use the current endpoint for gene and variant pages.

**Comment by zhx828** [comment]
Current curation document has been updated by combining Biological effect and Clinical effect together.

**Comment by JiaoJiao123** [comment]
@zhx828 ok I see. yeah, the curation document has combined Biological and clinical effect together quite a while ago.
