### ISSUE TITLE
Removing aliases that are used as main hugo symbol

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#760]
Please give as much information as possible before submitting your issue - Thank you

Issue: 

Some of the current main hugo symbols (non-oncokb genes) maybe used as an alias for the oncokb genes. As a result, the API will add 

Example:

@schultzn  could you give an example -- the case you mentioned yesterday?

The complete hugo symbol list can be downloaded here: https://www.genenames.org/cgi-bin/statistics

Screenshot:

**Comment by zhx828** [comment]
@jjgao do we have a better solution? Shouldn't we also map these 'hugoSymbol' like gene alias? And also portal is using entrezGeneId, we are not sending hugoSymbol anymore, this shouldn't be the issue. @schultzn could you give me an example? Thanks!

**Comment by jjgao** [comment]
@zhx828 It's not a portal issue. When we annotate a MAF, entrez gene IDs may not be available. In general, if a symbol is an official hugo symbol, it's a good idea to assign it to that gene and remove it from other genes's aliases list anyway.

**Comment by zhx828** [comment]
Sounds good. I have created the pipeline in OncoKB. Will fix the data
tomorrow.

Hongxin

**Comment by zhx828** [comment]
https://github.com/oncokb/oncokb/pull/757 is designed to solve the issue.
