### ISSUE TITLE
Enhancement Feature - Dragging Tabs

### ISSUE THREAD

**Issue by phillis2** [oncokb/oncokb#77]
Many curators have asked if we could drag sections of information to move them around the curation. Currently if something is in the wrong place (e.g. an investigational description), we have to copy the information and manually retype the tumor type and drug name in the correct location; then we have to delete the old info. It would be much easier if we could just drag the entire section to its correct location.

Not a high priority (but would be a great feature)

**Comment by zhx828** [comment]
N/A
