### ISSUE TITLE
entrez_gene_id in Evidence model will be set to 0 if passed in as null

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#839]

**Comment by zhx828** [comment]
@JiaoJiao123 entrez_gene_id is required by the database, do you think you can pass in entrez_gene_id when updating the evidence?

**Comment by JiaoJiao123** [comment]
@zhx828 The entrezGeneId is already passed in if the gene meta API runs successfully. 
But there should be an option to query by hugoSymbol only. Could we pass in an invalid entrezGeneId(such as a certain negative number) to indicate that we want to skip query by entrezGeneId?

**Comment by zhx828** [comment]
@JiaoJiao123 I see. I wouldn't suggest that. This should be fixed by me. I can't ask other users do the same thing as well.
