### ISSUE TITLE
Truncating mutations are not displayed in mutation diagram

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#850]
Please give as much information as possible before submitting your issue - Thank you

Issue: 
Truncating mutations are not displayed in mutation diagram

Example:
http://oncokb.org/#/gene/TP53

Screenshot:
![image](https://user-images.githubusercontent.com/840895/33618704-423e8738-d9b1-11e7-8a95-a7bd7b7fe0d5.png)

**Comment by JiaoJiao123** [comment]
@jjgao Looking into this

**Comment by JiaoJiao123** [comment]
@jjgao May I confirm something? Do you mean the exact variant 'Truncating mutations' or variants with truncating consequences such as X33_splice?

**Comment by jjgao** [comment]
for example, TP53 has many truncating mutations (http://www.cbioportal.org/index.do?session_id=595408da498e5df2e291c896&show_samples=false&) in cbioportal, but none of them are displayed on http://oncokb.org/#/gene/TP53.

It should look exactly like the one below, except most of the missense mutations outside P53 domain.

![image](https://user-images.githubusercontent.com/840895/33724851-8e7c678a-db3e-11e7-84a9-241734462c42.png)
