### ISSUE TITLE
Errors from using the hotfix backend after portal alteration import

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#877]
![screen shot 2017-12-27 at 1 35 37 pm](https://user-images.githubusercontent.com/13951023/34389998-e6ab8432-eb0a-11e7-9b27-cfa6d5806609.png)
![screen shot 2017-12-27 at 1 32 52 pm](https://user-images.githubusercontent.com/13951023/34389926-826af818-eb0a-11e7-84a7-5935d8a159b9.png)

**Comment by zhx828** [comment]
Seems like this issue is gone in production. Close for now.
