### ISSUE TITLE
API calls was fired and returned as success but database is not updated

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#891]
As you can see in "localhost_access_log.2018-01-11.txt", there are 3 records in logs like below:
"POST /internal/legacy-api/evidences/update HTTP/1.1" 200, which corresponding to the 3 newly added truncating mutation in the curation platform in FOXA1, BIRC3 and AMER1 on Jan/11/2018.

**Comment by zhx828** [comment]
This issue will be solved after merging rc branch.

**Comment by zhx828** [comment]
This issue was caused due to he isDesiedGene check. Now we removed the check to the backend.
