### ISSUE TITLE
filter out hexadecimal code in string in curation platform

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#897]
Please give as much information as possible before submitting your issue - Thank you

Issue: 

Example:

Screenshot:

**Comment by JiaoJiao123** [comment]
@zhx828 I checked 6 folders around the time that the issued happened but failed to reproduce the issue. I will investigate this if it happens again.

**Comment by zhx828** [comment]
Couldn't reproduce the issue, close for now.
