### ISSUE TITLE
Switch to PDF library that support special characters

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb#943]
We are using ispdf as the library to generate PDF files but it can not process special characters such as Greek letters. So we need to replace this library.

**Comment by zhx828** [comment]
The library seems to support base64 characters now. Maybe take a quick look and upgrade? https://github.com/MrRio/jsPDF/issues/1830

**Comment by zhx828** [comment]
Don't have the bandwidth upgrading. Close for now.
